void main(List<String> args) {
  
  num a1= 10;
  num a2=10.5;

  int a3=10;
  double a4=10.5;

//string
String s1= " test ' 1";
String s2= 'test2 \' gghhjb';

//string interpolation dart
String s3="test $a1 and ${a1+a2}";
String s4="test "+a1.toString()+" and "+(a1+a2).toString();

print(s3);
print(s4);

//boolean
bool b1=true;
bool b2=false;

//List
List<int> l1=[1,2,3];
print(l1[0]);
List<String> l2=["ali","mohammad","hasan"];
List<bool> l3=[true,false];
List<int> autoGeneratedList1=List.generate(5, (index) => index*5,growable: true);
List<int> autoGeneratedList2=List.filled(5, 0,growable: true);
List fromOthers=[...l1,...autoGeneratedList1];

print(autoGeneratedList1);
print(fromOthers);

//Set
Set<int> set1={1,2,3,1};
Set set2 = Set.from(l1);
Set set3=Set.of(l2);
print(set1);

//map
Map<String,int> m1={
  "key1":1,
  "key2":2
};
Map m2={
   "key3":3,
  "key4":4
};
Map combinedMap={...m1,...m2};
print(combinedMap);

//dynamic
dynamic d1=10;
dynamic d2=10.5;
dynamic d3="test";
d3=11;
print(d1);

//Object
Object o1={1,2,3};
Object o2={"a":1};

print(o1);
print(o2);
}